### PR TITLE
Cura 2 3

### PR DESCRIPTION
**Pull request by blakeatkins**

### CODE REVIEW

**Comment by machinekoder** [comment]
@blakeatkins Does this patch work?

**Comment by blakeatkins** [comment]
Hi Alexander,

It seems to have a few issues.  Print speed is too fast and post-print
commands fail to run. I hope to have them worked out soon.  Would you like
me to rework to keep the old as well?  Possibly find Cura version via
makefile and install the appropriate definitions?

Thanks,

--Blake

**Comment by machinekoder** [comment]
Hi Blake,

Thank you for the contribution. I think a new branch should be sufficient.

**Comment by machinekoder** [comment]
@blakeatkins I updated the master branch for Cura 2.3

**Pull request closed without merging**
